[package]
name = "lsdup"
version = "0.1.0"
authors = ["redsaz <redsaz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

blake3 = "0.1.0"
